export let colorsData = [
    { color: "red", checked: false },
    { color: "green", checked: false },
    { color: "blue", checked: false },
    { color: "yellow", checked: false },
    { color: "slate", checked: false },
    { color: "gray", checked: false },
    { color: "amber", checked: false },
    { color: "purple", checked: false },
    { color: "indigo", checked: false },
    { color: "zinc", checked: false },
    { color: "neutral", checked: false },
    { color: "stone", checked: false },
    { color: "lime", checked: false },
    { color: "emerald", checked: false },
    { color: "sky", checked: false },
    { color: "rose", checked: false },
    { color: "pink", checked: false },
];